### ISSUE TITLE
Add NFT20 To Dappradar

### ISSUE THREAD

**Issue by surfer77** [verynifty/bounties#1]
We are offering a bounty of $250 USDC for adding NFT20 details and contracts to Dappradar, feel free to ask here for any details you might need. 

After you submit the details to Dappradar, please post here that you did and a screenshot of the confirmation so we can keep track of it.

**Bounty will be paid when the listing is live.**

**Comment by grandsmarquis** [comment]
![photo5771377779223410562](https://user-images.githubusercontent.com/1624124/127545064-64863263-9a61-4bbb-87e0-69f21c3f5c65.jpg)

**Comment by notenea** [comment]
![Screenshot_93](https://user-images.githubusercontent.com/78374236/127550074-dce736a5-7498-45af-82da-53b3cb721d74.png)

**Comment by surfer77** [comment]
Paid bounty to ENEA

https://dappradar.com/ethereum/marketplaces/nft20

TX:  https://etherscan.io/tx/0xc741f4a4ea5ac7fdbfb8867b43965bc94119dce801702c4e2c0d156319f7d3b0
